language: java

jdk:
  - openjdk7

env:
  - NUODB_HOME=/opt/nuodb NUODB_MIGRATION_HOME=assembly/target/nuodb-migrator SOURCE_JDBCJAR=/var/tmp/mysql-connector-java-5.1.23.jar SOURCE_DRIVER=com.mysql.jdbc.Driver SOURCE_URL=jdbc:mysql://localhost:3306/nuodbtest SOURCE_USERNAME=root SOURCE_PASSWORD= NUODB_DRIVER=com.nuodb.jdbc.Driver NUODB_URL=jdbc:com.nuodb://localhost/test NUODB_USERNAME=dba NUODB_PASSWORD=goalie NUODB_SCHEMA=HOCKEY

notifications:
  recipients:
    - moorthy@asthra.com

before_install:
  - mysql -u$SOURCE_USERNAME -e 'create database nuodbtest;'
  - mysql -u$SOURCE_USERNAME nuodbtest < core/src/test/resources/mysql/nuodbtest.sql
  - wget -q http://www.nuodb.com/latest/nuodb-1.0-GA.linux.x86_64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_HOME}/bin/nuodb --chorus test --password bar --dba-user ${NUODB_USERNAME} --dba-password ${NUODB_PASSWORD} --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_HOME}/bin/nuodb --chorus test --password bar --dba-user ${NUODB_USERNAME} --dba-password ${NUODB_PASSWORD} &
  - sleep 2
  - wget -q http://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.23/mysql-connector-java-5.1.23.jar --output-document=${SOURCE_JDBCJAR}

install: mvn clean install

script:
  - cp ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator.orig
  - sed 's/bootstrap.jar/bootstrap.jar:${SOURCE_JDBCJAR}/g' ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator.orig > ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator
  - ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator dump --time.zone=EST --source.driver=${SOURCE_DRIVER} --source.url=${SOURCE_URL}  --source.catalog=nuodbtest --source.username=${SOURCE_USERNAME} --output.type=bson --output.path=/var/tmp/dump.cat
  - ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator schema --source.driver=${SOURCE_DRIVER} --source.url=${SOURCE_URL}  --source.catalog=nuodbtest --source.username=${SOURCE_USERNAME} --output.path=/var/tmp/dump.sql
  - ${NUODB_HOME}/bin/nuosql test@localhost --user ${NUODB_USERNAME} --password ${NUODB_PASSWORD} --schema ${NUODB_SCHEMA} < /var/tmp/dump.sql
  - ${NUODB_MIGRATION_HOME}/bin/nuodb-migrator load --time.zone=EST --target.url=${NUODB_URL} --target.username=${NUODB_USERNAME} --target.password=${NUODB_PASSWORD} --input.path=/var/tmp/dump.cat
  - mvn -Pmysql-integration-tests test

after_script:
  - mysql -u$SOURCE_USERNAME -e 'drop database nuodbtest;'
