language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

notifications:
  recipients:
    - moorthy@asthra.com
    - sergey.bushik@altoros.com
    - plothridge@nuodb.com

before_install:
  - ./test/mysql_setup.sh
  - ./test/nuodb_setup.sh

install: mvn -U clean install

script:
  - ./test/mysql_basic.sh

after_script:
  - mysql -u$SOURCE_USERNAME -e 'drop database nuodbtest;'