language: java

jdk:
  - openjdk8
  - oraclejdk8

notifications:
  recipients:
    - migrator@nuodb.com

before_install:
  - ./test/mysql_setup.sh
  - ./test/nuodb_setup.sh

install: mvn -U clean install

script:
  - ./test/mysql_basic.sh
  - ./test/batch_test.sh

